name: Deploy to AWS ECR and EC2

on:
  push:
    branches:
      - feat/*  # Change this if needed
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
          audience: sts.amazonaws.com

      #- name: Set up AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: eu-west-3  # Change this to your AWS region

      #- name: Log in to Amazon ECR
      #  run: |
      #    make login-ecr

      #- name: Build and push Docker image
      #  run: |
      #    make build-docker-image
      #    make push-docker-image

      #- name: add ssh-agent
      #  uses: webfactory/ssh-agent@v0.9.0
      #  with:
      #    ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List files in airflow-dags
        run: ls -l airflow-dags/

      #- name: Get Public IP of GitHub Runner
      #  run: curl -s https://checkip.amazonaws.com

      - name: Copy DAGs to EC2 via Bastion
        uses: appleboy/ssh-action@v1.2.0
        with: 
          host: ${{ secrets.BASTION_HOST }}  # Bastion public IP
          username: ec2-user  # or ubuntu depending on the host OS
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_HOST }} 
          proxy_username: ${{ secrets.EC2_USER }}
          script: |
            # ssh -o StrictHostKeyChecking=no -A ec2-user@${{ secrets.BASTION_HOST }} << 'EOF'
            # SCP command without specifying private key because of agent forwarding
            scp -o StrictHostKeyChecking=no airflow-dags/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/airflow/dags
            EOF

      #- name: Test SSH Connection to Bastion
      #  run: ssh -vvv -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_HOST }} "echo 'Connected to Bastion'"

      
      #- name: Deploy DAGs to EC2 via Bastion host
      #  run: |
          # set up SSH tunnel to the private ec2 via bastion host
      #    ssh -o StrictHostKeyChecking=no -A ec2-user@${{ secrets.BASTION_HOST }} << 'EOF'
      #    scp -o StrictHostKeyChecking=no airflow-dags/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/airflow/dags
      #    EOF


