name: Deploy to AWS ECR and EC2

on:
  push:
    branches:
      - feat/*  # Change this if needed
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
          audience: sts.amazonaws.com

      #- name: Set up AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: eu-west-3  # Change this to your AWS region

      - name: Log in to Amazon ECR
        run: |
          make login-ecr

      - name: Build and push Docker image
        run: |
          make build-docker-image
          make push-docker-image

      - name: Deploy DAGs to EC2 via Bastion Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BASTION_HOST }}  # Public IP of the bastion host
          username: ${{ secrets.BASTION_USER }}  # Username for the bastion host
          key: ${{ secrets.EC2_SSH_KEY }}  # Private SSH key
          source: "airflow-dags/*"
          target: "/home/${{ secrets.EC2_USER }}/airflow/dags"
          proxy_host: ${{ secrets.EC2_HOST }}  # Private IP of the target EC2 instance
          proxy_username: ${{ secrets.EC2_USER }}  # Username for the target EC2 instance
          proxy_port: 22
