
version: 2

models:
  - name: stg_medication
    description: "Medication data"
    columns:
      - name: medication_code
      - name: category
      - name: cost
      - name: created_at
      - name: updated_at
      - name: _ab_source_file_url
      - name: _ab_source_file_last_modified

  - name: stg_medications_prescriptions
    description: "Medication data"
    columns:
      - name: medication_prescription_id
      - name: medication_code
      - name: appointment_id
      - name: frequency
      - name: dosage
      - name: quantity

  - name: stg_procedure
    description: "procedure data"
    columns:
      - name: procedure_code
      - name: procedure_description
      - name: procedure_cost
      - name: updated_at
      - name: _ab_source_file_url
      - name: procedure_name
      - name: procedure_category
      - name: risk_level
      - name: created_at
      - name: _ab_source_file_last_modified

  - name: stg_procedures_performed
    description: "procedure data"
    columns:
      - name: procedure_performed_id
      - name: appointment_id
      - name: notes
      - name: created_at
      - name: procedure_code
      - name: duration
      - name: updated_at

  - name: stg_appointments
    description: "Appointments data"
    columns:
      - name: appointment_id
      - name: patient_id
      - name: doctor_id
      - name: appointment_date
      - name: appointment_type
        tests:
          - accepted_values:
              values: ['Routine Checkup', 'Follow-up Visit', 'Emergency Visit', 'Specialist Consultation', 'Telemedicine', 'Surgery', 'Vaccination', 'Mental Health Evaluation', 'Skin Consultation']
      - name: diagnosis
       # tests:
       #   - accepted_values:
       #       values: ['Hypertension', 'Diabetes Mellitus', 'Chronic Obstructive Pulmonary Disease (COPD)', 'Asthma', 'Coronary Artery Disease', 'Migraine', 'Anxiety Disorder', 'Depression', 'Osteoarthritis', 'Congestive Heart Failure', 'Pneumonia', 'Fracture of bone', 'Skin Infection', 'Urinary Tract Infection', 'Cerebral Palsy'] 
      - name: created_at
      - name: updated_at
      - name: _ab_source_file_url
      - name: _ab_source_file_last_modified

  - name: stg_departement
    description: "Department data"
    columns:
      - name: department_id
      - name: department_name
      - name: department_location
      - name: created_at
      - name: updated_at
      - name: _ab_source_file_url
      - name: _ab_source_file_last_modified

  - name: stg_doctors
    description: "Doctors data"
    columns:
      - name: doctor_id
      - name: first_name
      - name: last_name
      - name: specialization
      - name: department_id
      - name: hire_date
      - name: created_at
      - name: updated_at
      - name: _ab_source_file_url
      - name: _ab_source_file_last_modified

  - name: stg_patients
    description: "Patients data"
    columns:
      - name: patient_id
      - name: first_name
      - name: last_name
      - name: gender
      - name: dob
      - name: patient_address
      - name: city
      - name: country
      - name: created_at
      - name: updated_at
      - name: _ab_source_file_url
      - name: _ab_source_file_last_modified

  - name: int_appointment_medication
    description: "int_appointment_medication data"
    columns:
      - name: appointment_id
      - name: total_medications
      - name: total_medication_cost

  - name: int_appointment_procedure
    description: "int_appointment_procedure data"
    columns:
      - name: appointment_id
      - name: total_procedures
      - name: total_duration
      - name: total_procedure_cost

  - name: int_medication
    description: "int_medication data"
    columns:
      - name: medication_prescription_id
      - name: medication_code
      - name: frequency
      - name: dosage
      - name: category
      - name: created_at
      - name: updated_at

  - name: int_procedure
    description: "int_procedure data"
    columns: 
      - name: procedure_performed_id
      - name: notes
      - name: procedure_code
      - name: duration
      - name: procedure_description
      - name: procedure_name
      - name: procedure_category
      - name: risk_level
      - name: created_at
      - name: updated_at

  
  - name: fact_appointment
    description: "Appointments data"
    columns:
      - name: appointment_id
        tests:
          - unique
          - not_null
      - name: patient_id
        tests:
          - not_null
      - name: doctor_id
        tests:
          - not_null
      - name: appointment_date
      - name: appointment_type
        tests:
          - accepted_values:
              values: ['Routine Checkup', 'Follow-up Visit', 'Emergency Visit', 'Specialist Consultation', 'Telemedicine', 'Surgery', 'Vaccination', 'Mental Health Evaluation', 'Skin Consultation']
      - name: medication_count
      - name: total_medication_cost
      - name: procedure_count
      - name: total_procedure_cost
      - name: total_revenue
      - name: created_at
      - name: updated_at

  - name: dim_doctors
    description: "dim_doctors"
    columns:
      - name: doctor_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: hire_date
      - name: total_costs
      - name: updated_at
      - name: specialization
     # - name: department_id
      - name: created_at
  
  - name: dim_patients
    description: "dim_patients"
    columns:
      - name: patient_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: city
      - name: country
      - name: gender
      - name: dob
      - name: patient_address
      - name: created_at
      - name: updated_at
  
  - name: dim_procedure
    description: "dim_procedure"
    columns:
      - name: procedure_performed_id
        tests:
          - unique
          - not_null
      - name: notes
      - name: procedure_code
      - name: duration
      - name: procedure_description
      - name: procedure_name
      - name: procedure_category
      - name: risk_level
      - name: created_at
      - name: updated_at

  - name: dim_medication
    description: "dim_medication"
    columns:
      - name: medication_prescription_id
        tests:
          - unique
          - not_null
      - name: medication_code
      - name: frequency
      - name: dosage
      - name: category
      - name: created_at
      - name: updated_at

  - name: dim_departement
    description: "dim_departement"
    columns:
      - name: department_id
        tests:
          - unique
          - not_null
      - name: department_name
      - name: department_location
      - name: created_at
      - name: updated_at

sources:
  - name: healthcare
    schema: airbyte_internal
    tables:
      - name: public_raw__stream_dim_medication
      - name: public_raw__stream_dim_medications_prescriptions
      - name: public_raw__stream_dim_procedures_performed
      - name: public_raw__stream_dim_procedure
      - name: public_raw__stream_dim_appointments
      - name: public_raw__stream_dim_department
      - name: public_raw__stream_dim_doctors
      - name: public_raw__stream_dim_patients